id: P009197
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC331
  title: རྟ་ནག་ཅང་ཤེས།
  author: ''
  volumes:
    7585d02e0d3944bda10ddf578d53885a:
      image_group_id: I2PD19237
      title: ''
      volume_number: 1
      total_pages: 446
      base_file: v001.txt
