id: I689745C7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:24:11+00:00'
last_modified: '2022-06-08T09:18:36.332160+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC331
  title: རྟ་ནག་ཅང་ཤེས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    4F13:
      image_group_id: I2PD19237
      title: ''
      total_pages: 446
      order: 1
      base_file: 4F13.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
